// Public API
export { createPolo, registerSources } from "./polo.ts";
export type { PoloInstance } from "./polo.ts";

// Public types
export type {
  AnySchema,
  AnySource,
  AnyInput,
  AnyResolverSource,
  Chunk,
  ChunkSource,
  ChunkRecord,
  Chunks,
  DependentChunkSourceConfig,
  DependentSourceConfig,
  Definition,
  DeriveFn,
  EnforceSourceDependencies,
  ExcludeDecision,
  FromInputSourceOptions,
  InferContext,
  InferSchemaInput,
  InferSchemaInputObject,
  InferSchemaOutput,
  InferSchemaOutputObject,
  InferSource,
  InferSources,
  InputSchema,
  InputSource,
  Policies,
  PolicyExcludeFn,
  PoloLogger,
  PoloOptions,
  PolicyRecord,
  PromptOutput,
  PromptTrace,
  RenderableValue,
  ResolverSource,
  Resolution,
  SourceConfig,
  SourceDepValues,
  SourceResolveArgs,
  SourceSet,
  SourceSetBrand,
  SourceSetSources,
  SourceTag,
  SourceShape,
  ChunkSourceConfig,
  SourceOptions,
  SourceRecord,
  SourceRecordType,
  TemplateFn,
  TemplateContext,
  Trace,
  ValueSource,
} from "./types.ts";

// Errors
export {
  CircularSourceDependencyError,
  MissingSourceDependencyError,
  RequiredSourceMissingError,
  SourceResolutionError,
} from "./errors.ts";
